# -*- coding: utf-8 -*-
"""Practical_1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdgMTi3Jvt1Nr6yMSKddkYNcdAFQrisV

# Implement Find-S Algorithm

## Load Libraries
"""

import pandas as pd

"""## Load Dataset"""

df = pd.read_csv('tennis.csv')

"""## Explore Dataset"""

df.head()

df.shape

df.info()

for i in df.columns:
    print(f'{i} : {df[i].unique()}')

"""## Split Dataset Into Attributes And Target"""

result=df['play'].values

attributes=df.drop('play',axis=1).values

"""## Initialization Of Specific Hypothesis"""

H=['0']*attributes.shape[1]

print(f'Initial Hypothesis is : {H}')

"""## Implement The Logic Of Find-S Algorithm"""

for i in range(attributes.shape[0]):
    if result[i]=='yes':
        for j in range(attributes.shape[1]):
            if H[j]=='0':
                H[j]=attributes[i][j]
            elif H[j]!=attributes[i][j]:
                H[j]='?'
    print(f'For Step-{i} : {H}')

"""## Final General Hypothesis"""

print(f'Final Hypothesis is : {H}')