# -*- coding: utf-8 -*-
"""prct_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX8qBkojrJbY7sLpaK7ZkwSxMmvgFT-K
"""

#!pip install scikit-learn nltk

import nltk

import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

print(stop_words)

#1. Sample data (replace / expand this with real data as needed)
texts = [
"I love the movie. It was fantastic!",
"What a terrible movie. I hated it.",
"An excellent film with a great cost.",
"Worst film ever. Not recommended.",
"Such an amazing experience, will watch again!",
"It was boring and too long.",
"Brilliant direction and storyline!",
"I didn't enjoy the movie at all.",
"The plot was dull and predictable.",
"Aboslutely loved it, great acting1"
]

labels = [1, 0, 1, 0, 1, 0, 1, 0, 0, 1]  # 1 = Positive, 0 = Negative

#2. Text Preprocessing
def preprocess(text):
    text = re.sub(r'<.*?>','', text) #remove HTML
    text = re.sub(r'[^a-zA-Z]',' ', text) # remove special charecters
    text = text.lower()
    text = text.lower()
    tokens = text.split()
    tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

cleaned_texts = [preprocess(text) for text in texts]

print(cleaned_texts)

#3. Convert text to numerical features
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(cleaned_texts)
y = labels

#4. Split into training and testing sets
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#5. Train a model
model = LogisticRegression()
model.fit(X_train, y_train)

#6. Evaluate
y_pred = model.predict(X_test)
#print("Classification Report:\n", classification_report(y_test, y_pred))
print(classification_report(
    y_test,
    y_pred,
    zero_division=0
))

#7. Predict on new text
def predict_sentiment(text):
    cleaned = preprocess(text)
    vector = vectorizer.transform([cleaned])
    pred = model.predict(vector)[0]
    return "Positive" if pred == 1 else"Negative"

#8. Test
print("\nTest Predictions:")
print(predict_sentiment("That was an awesome movie!"))
print(predict_sentiment("I regret watching it."))

