# -*- coding: utf-8 -*-
"""Adv.Ai.pract_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14tmTSILfY8tUM9pWMee1dwMUEA9g5Und
"""

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import os

# Load model
model = YOLO("yolov5s.pt")  # auto-downloads if missing

# Load image
image_path = os.path.abspath("person.jpg")
image = cv2.imread(image_path)

if image is None:
    raise FileNotFoundError(f"Could not load image: {image_path}")

# BGR -> RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Inference
results = model.predict(image_rgb, conf=0.5)

# Visualization
annotated = results[0].plot()  # already RGB
plt.imshow(annotated)
plt.axis("off")
#plt.show()

